### ISSUE TITLE
Amount get rounded

### ISSUE THREAD

**Issue by jadeja-rajdeep** [cardstream/WooCommerce#1]
Hello dev

for example if order amount is 4.95 GBP when your code send the amount to payment gateway its get rounded to 4 GBP

founded bug in this place

public function capture_order($order_id) {
        $order     = new WC_Order($order_id);
        //$amount    = (int) round($order->get_total(), 2) * 100;
        $amount    = (int) (round($order->get_total(), 2) * 100);

i just wrap the calculation code and then convert to (int) which solve the issue

Thanks

**Comment by cardstreamltd** [comment]
Thanks for spotting this, we'll get it updated asap!
